version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Calculator
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
